pipeline:
  name: CodeQL Analysis
  identifier: codeql_analysis
  projectIdentifier: default
  orgIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: monorepo
        repoName: poc-codeql-wrapper

  stages:
    - stage:
        name: CodeQL
        identifier: security_analysis
        type: CI
        spec:
          caching:
            enabled: false
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Python
                  identifier: install_python
                  spec:
                    shell: Bash
                    command: |
                      chmod +x ./install_python.sh
                      ./install_python.sh

              - step:
                  type: Run
                  name: Install CodeQL Wrapper
                  identifier: install_codeql_wrapper
                  spec:
                    shell: Bash
                    command: |
                      pip install -i https://test.pypi.org/simple/ codeql-wrapper
                      codeql-wrapper --version

              - step:
                  type: Run
                  name: Run CodeQL Analysis
                  identifier: run_codeql_analysis
                  spec:
                    shell: Bash
                    envVariables:
                      GITHUB_TOKEN: <+secrets.getValue("PAT")>
                    command: |
                      codeql-wrapper --verbose analyze ./monorepo --monorepo --upload-sarif

          platform:
            os: Linux
            arch: Amd64

          runtime:
            type: Cloud
            spec: {}
