name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1.0.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Swatinem/rust-cache@v1.0.1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true
      - run: cd kalk; cargo build --target wasm32-unknown-unknown --no-default-features