pipeline {
    agent any
    
    environment {
        GITHUB_TOKEN = credentials('codeql-wrapper-token')
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Setup Python') {
            steps {
                sh '''#!/bin/bash                    
                    # Upgrade pip, setuptools, and wheel
                    python3 -m venv venv
                    . venv/bin/activate
                    
                    echo "Upgrading pip, setuptools, and wheel..."
                    python3 -m pip install --upgrade --force-reinstall pip setuptools wheel packaging gitpython
                    
                    python3 -m pip install --upgrade pip
                     pip install -i https://test.pypi.org/simple/ --force-reinstall codeql-wrapper
                '''
            }
        }
        
        stage('CodeQL Analysis') {
            steps {
                sh '''#!/bin/bash
                    . venv/bin/activate
                    
                    codeql-wrapper analyze ./monorepo --monorepo --upload-sarif --verbose
                '''
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'codeql-results/**/*', allowEmptyArchive: true
        }
    }
}
