pipeline {
    agent any
    
    environment {
        GITHUB_TOKEN = credentials('codeql-wrapper-token')
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Setup Python') {
            steps {
                sh '''#!/bin/bash                    
                    # Upgrade pip, setuptools, and wheel
                    python3 -m venv venv
                    . venv/bin/activate

                    pip uninstall codeql-wrapper -y
                    
                    echo "Upgrading pip, setuptools, and wheel..."
                    python3 -m pip install --upgrade --force-reinstall pip setuptools wheel packaging gitpython==3.1.45
                    pip install --extra-index-url https://test.pypi.org/simple/ codeql-wrapper==0.2.15
                '''
            }
        }
        
        stage('CodeQL Analysis') {
            steps {
                sh '''#!/bin/bash
                    . venv/bin/activate
                    echo "Base Ref (Target Branch): ${env.CHANGE_TARGET}"
                    echo "Ref (Source Branch): ${env.CHANGE_BRANCH}"
                    
                    codeql-wrapper --verbose analyze ./monorepo --monorepo --upload-sarif --ref ${env.CHANGE_BRANCH} --base-ref ${env.CHANGE_TARGET}
                '''
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'codeql-results/**/*', allowEmptyArchive: true
        }
    }
}
