# Workflow for scanning code with CodeQL
name: test-codeql-wrapper-monorepo-json

# Trigger workflow
on:
  workflow_dispatch:

jobs:
  codeql-analysis:
    name: codeql-wrapper-monorepo-json
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # https://test.pypi.org/project/codeql-wrapper/
    - name: Install CodeQL Wrapper
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -i https://test.pypi.org/simple/ codeql-wrapper
        codeql-wrapper --version
    
    - name: Run CodeQL Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        codeql-wrapper --verbose analyze . --monorepo --upload-sarif
