# Workflow for scanning code with CodeQL
name: test-codeql-wrapper-monorepo

# Trigger workflow
on:
  workflow_dispatch:

jobs:
  codeql-analysis:
    name: codeql-wrapper-monorepo
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove .codeql.json
      run: rm -f .codeql.json      

    - name: Install Python
      run: |
        chmod +x ./install_python.sh
        ./install_python.sh

    # https://test.pypi.org/project/codeql-wrapper/
    - name: Install CodeQL Wrapper
      run: |
        pip install -i https://test.pypi.org/simple/ codeql-wrapper
        codeql-wrapper --version
    
    - name: Run CodeQL Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        codeql-wrapper --verbose analyze ./monorepo --monorepo --upload-sarif
